{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cadquery as cq\n",
    "from cadquery import Workplane, Assembly, Location, Vector, Color, exporters\n",
    "\n",
    "\n",
    "from ocp_vscode import show, show_object, reset_show, set_port, set_defaults, get_defaults\n",
    "set_port(3939)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [],
   "source": [
    "reset_show()\n",
    "um = 0.001  # unit multiplier for mm to meters"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define parameters for the design\n",
    "# These parameters can be adjusted as needed\n",
    "bar_width = 300*um\n",
    "bar_length = 2000*um\n",
    "bar_thickness = 20*um\n",
    "gap = 2000*um\n",
    "\n",
    "top_bar_width = 2300*um\n",
    "top_bar_length = 300*um\n",
    "\n",
    "c_bridge_width = 300*um\n",
    "c_bridge_length = 450*um\n",
    "\n",
    "pad_length = 200*um # This is a parameter\n",
    "\n",
    "signal_pad_length = 550*um\n",
    "\n",
    "via_r = (c_bridge_width/2)\n",
    "via_thickness = 20*um # This is a parameter\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Make the Open Structure"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c\n",
      "cc\n",
      "ccc\n",
      "cccc\n",
      "ccccc\n"
     ]
    }
   ],
   "source": [
    "reset_show()\n",
    "def make_cal_open(pad_length = 200*um,DI_thickness = 20*um):\n",
    "    \"\"\"Create a calibration open structure for the design.\"\"\"\n",
    "    open_bot = Assembly()\n",
    "    open_signal_pad = Assembly()\n",
    "    open_top_electrode = Assembly()\n",
    "    open_via = Assembly()\n",
    "    open_DI = Assembly()\n",
    "\n",
    "    output = Assembly()\n",
    "\n",
    "    wp = Workplane(\"XY\")\n",
    "    left_bar = (\n",
    "        wp.rect(bar_width, bar_length,centered=False)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "    right_bar = (\n",
    "        wp.move(gap, 0)\n",
    "        .rect(bar_width, bar_length,centered=False)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "    top_bar = (\n",
    "        wp.moveTo(0,0)\n",
    "        .move(0,bar_length)\n",
    "        .rect(top_bar_width,top_bar_length,centered=False)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "    c_bridge = (\n",
    "        wp.move(gap/2,bar_length)\n",
    "        .rect(c_bridge_width,-c_bridge_length,centered=False)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "    c_pad = (\n",
    "        wp.moveTo((top_bar_width/2),(bar_length - c_bridge_length)-pad_length/2)\n",
    "        .rect(pad_length,pad_length,centered=True)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "\n",
    "    bot_ci = left_bar.union(right_bar).union(top_bar).union(c_bridge).union(c_pad)\n",
    "\n",
    "    # The Signal Pad\n",
    "    signal_pad = (\n",
    "        wp.move(gap/2,0)\n",
    "        .rect(bar_width,signal_pad_length,centered=False)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "    # The Top CI\n",
    "    \"\"\" top_electrode = (\n",
    "        wp.workplane(offset=DI_thickness+bar_thickness)\n",
    "        .moveTo((top_bar_width/2),(bar_length - c_bridge_length)-pad_length/2)\n",
    "        .rect(pad_length, pad_length, centered=True)\n",
    "        .extrude(bar_thickness)\n",
    "    ) \"\"\"\n",
    "\n",
    "    top_connector = (\n",
    "        wp.workplane(offset=DI_thickness+bar_thickness)\n",
    "        .moveTo((top_bar_width/2 -c_bridge_width/2 ),(bar_length - c_bridge_length - pad_length))\n",
    "        .rect(c_bridge_width,-(bar_length-c_bridge_length-pad_length-signal_pad_length),centered=False)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "    top_CI = top_connector\n",
    "    \n",
    "    # The Via\n",
    "    via = (\n",
    "        wp.moveTo((top_bar_width/2),signal_pad_length)\n",
    "        .circle(via_r)\n",
    "        .extrude(DI_thickness+2*bar_thickness)\n",
    "    )\n",
    "\n",
    "    # The DI Layer\n",
    "    c_pad_tl = (\n",
    "        c_pad.faces(\">Z\")\n",
    "        .vertices(\"<X and >Y\")\n",
    "        .val()\n",
    "        .Center()\n",
    "    )\n",
    "    DI = (\n",
    "        wp.moveTo(c_pad_tl.x - 100*um, c_pad_tl.y + 100*um)\n",
    "        .rect(pad_length+200*um,-(bar_length - c_bridge_length - bar_width),centered=False)\n",
    "        .extrude(DI_thickness+bar_thickness)\n",
    "    )\n",
    "    open_bot = open_bot.add(bot_ci, name=\"bot_ci\", color = Color(\"gray\"))\n",
    "    open_signal_pad = open_signal_pad.add(signal_pad, name=\"signal_pad\", color = Color(\"gray\"))\n",
    "    open_top_electrode = open_top_electrode.add(top_CI, name=\"top_electrode\", color = Color(\"gray\"))\n",
    "    open_DI = open_DI.add(DI, name=\"DI\", color = Color(\"Quantity_NOC_DARKGOLDENROD2\"))\n",
    "    open_via = open_via.add(via, name=\"via\", color = Color(\"gray\"))\n",
    "\n",
    "    output = output.add(open_bot, name=\"bot_ci\").add(open_signal_pad, name=\"signal_pad\").add(open_top_electrode, name=\"top_electrode\").add(open_DI, name=\"DI\").add(via, name=\"via\")\n",
    "\n",
    "    show_object(open_bot, name=\"bot_ci\")\n",
    "    show_object(open_signal_pad, name=\"signal_pad\")\n",
    "    show_object(open_top_electrode, name=\"top_electrode\")\n",
    "    show_object(open_via, name=\"via\")\n",
    "    show_object(open_DI, name=\"DI\")\n",
    "    return(open_bot, open_signal_pad, open_top_electrode,open_via, open_DI, output)\n",
    "\n",
    "\n",
    "# Run code\n",
    "open_bot, open_signal_pad, open_top_electrode, open_DI, output = make_cal_open(DI_thickness=bar_thickness)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "output.save(\"cal_open.step\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Make the Calibration Structure"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c\n",
      "cc\n",
      "ccc\n",
      "cccc\n",
      "cccc+\n",
      "cccccc\n"
     ]
    }
   ],
   "source": [
    "reset_show()\n",
    "def make_cal_short(pad_length = 200*um ,DI_thickness = 20*um):\n",
    "    \"\"\"Create a calibration short structure for the design.\"\"\"\n",
    "    short_bot = Assembly()\n",
    "    short_signal_pad = Assembly()\n",
    "    short_top_electrode = Assembly()\n",
    "    short_via = Assembly()\n",
    "    short_s_via = Assembly()\n",
    "    short_DI = Assembly()\n",
    "\n",
    "    output = Assembly()\n",
    "\n",
    "    wp = Workplane(\"XY\")\n",
    "    left_bar = (\n",
    "        wp.rect(bar_width, bar_length,centered=False)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "    right_bar = (\n",
    "        wp.move(gap, 0)\n",
    "        .rect(bar_width, bar_length,centered=False)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "    top_bar = (\n",
    "        wp.moveTo(0,0)\n",
    "        .move(0,bar_length)\n",
    "        .rect(top_bar_width,top_bar_length,centered=False)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "    c_bridge = (\n",
    "        wp.move(gap/2,bar_length)\n",
    "        .rect(c_bridge_width,-c_bridge_length,centered=False)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "    c_pad = (\n",
    "        wp.moveTo((top_bar_width/2),(bar_length - c_bridge_length)-pad_length/2)\n",
    "        .rect(pad_length,pad_length,centered=True)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "\n",
    "    bot_ci = left_bar.union(right_bar).union(top_bar).union(c_bridge).union(c_pad)\n",
    "\n",
    "    # The Signal Pad\n",
    "    signal_pad = (\n",
    "        wp.move(gap/2,0)\n",
    "        .rect(bar_width,signal_pad_length,centered=False)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "    # The Top CI\n",
    "    top_electrode = (\n",
    "        wp.workplane(offset=DI_thickness+bar_thickness)\n",
    "        .moveTo((top_bar_width/2),(bar_length - c_bridge_length)-pad_length/2)\n",
    "        .rect(pad_length, pad_length, centered=True)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "\n",
    "    top_connector = (\n",
    "        wp.workplane(offset=DI_thickness+bar_thickness)\n",
    "        .moveTo((top_bar_width/2 -c_bridge_width/2 ),(bar_length - c_bridge_length - pad_length))\n",
    "        .rect(c_bridge_width,-(bar_length-c_bridge_length-pad_length-signal_pad_length),centered=False)\n",
    "        .extrude(bar_thickness)\n",
    "    )\n",
    "    top_CI = top_electrode.union(top_connector)\n",
    "    \n",
    "    # The Via\n",
    "    via = (\n",
    "        wp.moveTo((top_bar_width/2),signal_pad_length)\n",
    "        .circle(via_r)\n",
    "        .extrude(DI_thickness+2*bar_thickness)\n",
    "    )\n",
    "    # Shorted Via\n",
    "    # Find the center of the top face of c_pad\n",
    "    c_pad_top_face_center = (\n",
    "        c_pad.faces(\">Z\")  # Select the top face of c_pad\n",
    "        .workplane(centerOption=\"CenterOfMass\")  # Create a workplane at the center of mass\n",
    "        .val()  # Get the face\n",
    "        .Center()  # Get the center of the face as a vector\n",
    "    )\n",
    "\n",
    "    # Create an independent s_via at the center of the c_pad's top face\n",
    "    s_via = (\n",
    "        Workplane(\"XY\")  # Start a new workplane\n",
    "        .moveTo(c_pad_top_face_center.x, c_pad_top_face_center.y)  # Move to the center of the top face\n",
    "        .circle(100 * um)  # Create a circle with radius 100 um\n",
    "        .extrude(DI_thickness + bar_thickness)  # Extrude with the specified thickness\n",
    "    )\n",
    "\n",
    "    # The DI Layer\n",
    "    c_pad_tl = (\n",
    "        c_pad.faces(\">Z\")\n",
    "        .vertices(\"<X and >Y\")\n",
    "        .val()\n",
    "        .Center()\n",
    "    )\n",
    "    DI = (\n",
    "        wp.moveTo(c_pad_tl.x - 100*um, c_pad_tl.y + 100*um)\n",
    "        .rect(pad_length+200*um,-(bar_length - c_bridge_length - bar_width),centered=False)\n",
    "        .extrude(DI_thickness+bar_thickness)\n",
    "    )\n",
    "    short_bot = short_bot.add(bot_ci, name=\"bot_ci\", color = Color(\"gray\"))\n",
    "    short_signal_pad = short_signal_pad.add(signal_pad, name=\"signal_pad\", color = Color(\"gray\"))\n",
    "    short_top_electrode = short_top_electrode.add(top_CI, name=\"top_electrode\", color = Color(\"gray\"))\n",
    "    short_DI = short_DI.add(DI, name=\"DI\", color = Color(\"Quantity_NOC_DARKGOLDENROD2\"))\n",
    "    short_via = short_via.add(via, name=\"via\", color = Color(\"gray\"))\n",
    "    short_s_via = short_s_via.add(s_via, name=\"shorted_via\", color = Color(\"gray\"))\n",
    "\n",
    "    output = output.add(open_bot, name=\"bot_ci\").add(open_signal_pad, name=\"signal_pad\").add(open_top_electrode, name=\"top_electrode\").add(open_DI, name=\"DI\").add(via, name=\"via\").add(s_via, name=\"shorted_via\")\n",
    "\n",
    "    show_object(short_bot, name=\"bot_ci\")\n",
    "    show_object(short_signal_pad, name=\"signal_pad\")\n",
    "    show_object(short_top_electrode, name=\"top_electrode\")\n",
    "    show_object(short_via, name=\"via\")\n",
    "    show_object(short_s_via, name=\"shorted_via\")\n",
    "    show_object(short_DI, name=\"DI\")\n",
    "    return(short_bot, short_signal_pad, short_top_electrode, short_DI, short_via, short_s_via, output)\n",
    "\n",
    "\n",
    "# Run code\n",
    "short_bot, short_signal_pad, short_top_electrode, short_DI, short_via, short_s_via, output = make_cal_short(DI_thickness=bar_thickness)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "++++++++++\n"
     ]
    }
   ],
   "source": [
    "def generate_3d_text(thickness, value_range, orientation):\n",
    "    # Create an empty assembly to hold all the text objects\n",
    "    assembly = cq.Assembly()\n",
    "\n",
    "    # Determine placement based on orientation\n",
    "    if orientation == 'horizontal':\n",
    "        offset = 0\n",
    "        step = 10  # Horizontal spacing between numbers\n",
    "    else:\n",
    "        offset = 0\n",
    "        step = -10  # Vertical spacing (negative for downward)\n",
    "\n",
    "    # Generate text for each number in the range\n",
    "    for i in range(value_range[0], value_range[1] + 1):\n",
    "        # Create a text object for the current number\n",
    "        text = cq.Workplane(\"XY\").text(str(i), 2, thickness)  # '10' is the size of the text\n",
    "\n",
    "        # Place the text object in the assembly\n",
    "        if orientation == 'horizontal':\n",
    "            placement = (offset, 0, 0)\n",
    "        else:\n",
    "            placement = (0, offset, 0)\n",
    "\n",
    "        assembly.add(text, loc=cq.Location(cq.Vector(*placement)))\n",
    "\n",
    "        # Update the offset for the next number\n",
    "        offset += step\n",
    "\n",
    "    # Return the assembly\n",
    "    return assembly\n",
    "reset_show()\n",
    "result = generate_3d_text(20*0.001, (1, 10), 'horizontal')\n",
    "show_object(result)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
